"""Tests for src.physics.level_ratio_fit.

What is defended here is not "the fit converged" — with two free parameters it
always does — but that the module keeps the promises that make the answer mean
something:

* **A short ladder buys nothing.** Two measured levels and a free offset are
  reproduced exactly by every geometry in the list. The guard that refuses to
  rank in that case is the single most important behaviour in the module, and
  it is tested from both sides: refused with a fitted offset, allowed with a
  fixed one.
* **Ratios survive the junction.** A bias-independent lever arm rescales every
  level by the same factor, so it must move ``scale`` and nothing else — not
  chi-squared, not the AIC ordering, not the headline ratio.
* **Charging does not survive it.** A term growing with the level index is
  absorbable by neither a multiplier nor a constant, so it must show up as
  residual, and it must push successive ratios towards 1.
* **NaN, never a number.** A geometry of two lengths, a non-positive scale or
  a non-positive ground level report NaN rather than a plausible float.

Three regressions worth naming, all of the kind that would produce a confident
wrong answer rather than an error:

* a level whose error bar is infinite used to be floored at ``MIN_SIGMA_EV``
  and so became the *most* heavily weighted point in the fit — the weight is
  1/sigma^2, and the flooring was applied to non-finite sigmas as well as to
  zero ones;
* ``box_energies_1d`` and ``box_energies_3d`` return joules, so inverting a
  fitted scale through them would give a positive, plausible-looking length
  wrong by ten orders of magnitude;
* a square 2D box contains the 1D ladder exactly (its ``(n, 1)`` family is
  ``n^2 + 1``, and the constant shift is what the fitted offset absorbs), so a
  perfect 1D spectrum must come back ``'ambiguous'`` on a short ladder and
  only become conclusive once the ladder outruns the 2D pattern.

T.R.A.N.S. - Tools for Research and Analysis for Nano Spectroscopy
"""

from __future__ import annotations

import numpy as np
import pytest
from scipy.constants import e, hbar, m_e, pi

from src.physics.level_patterns import (LevelPattern, PATTERN_NAMES,
                                        all_patterns, pattern)
from src.physics.level_ratio_fit import (AMBIGUITY_DELTA_AIC, AMBIGUOUS,
                                         CONCLUSIVE, MIN_SIGMA_EV,
                                         TIE_QUANTUM, UNDERDETERMINED,
                                         VERDICTS, PatternFit, fit_pattern,
                                         rank_patterns, ratio_with_error,
                                         size_from_scale)

#: A ground level and a band-edge reference of the size a real dI/dV shows:
#: states tens of meV above an edge that is itself tens of meV from E_F.
SCALE_EV = 0.060
OFFSET_EV = 0.020

#: Disorder amplitude quoted in the module's precision figure. It is the
#: number to feed the fit, not k_B*T (~8 meV at 94 K) — the levels move by
#: more than the resolution smears them.
DISORDER_EV = 0.022


def _ladder(name, n, scale=SCALE_EV, offset=OFFSET_EV, n_levels=8):
    """A noiseless measured ladder generated by one geometry.

    ``E[k] = scale * ratios[k] + offset`` — exactly the model, so anything the
    fit fails to recover is a defect and not a statistical accident.
    """
    p = pattern(name, n_levels)
    return np.array([scale * r + offset for r in p.ratios[:n]], dtype=np.float64)


def _fake_pattern(ratios, name="two_lengths", dims=2):
    """A LevelPattern whose ratios belong to no single-length geometry.

    Built by hand rather than by adding to :mod:`level_patterns`, because the
    point is precisely what happens for a shape that file does not ship.
    """
    n = len(ratios)
    return LevelPattern(name=name, label=name, confined_dims=dims,
                        ratios=tuple(float(r) for r in ratios),
                        degeneracies=(1,) * n,
                        quantum_numbers=tuple((1, 1) for _ in range(n)))


# ---------------------------------------------------------------------------
# The model, and the algebra it promises
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("name", PATTERN_NAMES)
def test_a_noiseless_ladder_returns_the_geometry_that_made_it(name):
    """Every geometry must identify itself from its own perfect ladder, with
    the scale and the band-edge offset recovered exactly."""
    levels = _ladder(name, 5)
    verdict = rank_patterns(levels, 0.003)

    assert verdict.best is not None
    assert verdict.best.pattern == name
    assert verdict.best.chi2 == pytest.approx(0.0, abs=1e-12)
    assert verdict.best.scale_ev == pytest.approx(SCALE_EV, rel=1e-9)
    assert verdict.best.offset_ev == pytest.approx(OFFSET_EV, rel=1e-9, abs=1e-12)


def test_a_perfect_fit_uses_the_pattern_entries_in_order():
    levels = _ladder("box_1d", 4)
    fit = fit_pattern(levels, 0.003, pattern("box_1d"))

    assert fit.assignment == (0, 1, 2, 3)
    assert fit.n_skipped == 0
    assert fit.dof == 2                      # n - k, k = 2
    assert fit.rms_ev == pytest.approx(0.0, abs=1e-12)
    assert np.allclose(fit.residuals_ev, 0.0, atol=1e-12)


def test_chi2_is_the_weighted_sum_of_the_residuals_it_reports():
    """An exact identity: the reported residuals and chi-squared must be the
    same fit, not two independently computed ones."""
    levels = _ladder("box_2d_square", 5) + np.array([0.004, -0.003, 0.006,
                                                     -0.002, 0.001])
    sigma = 0.005
    fit = fit_pattern(levels, sigma, pattern("box_2d_square"))

    residuals = np.asarray(fit.residuals_ev)
    assert fit.chi2 == pytest.approx(float(np.sum((residuals / sigma) ** 2)),
                                     rel=1e-12)
    assert fit.rms_ev == pytest.approx(float(np.sqrt(np.mean(residuals ** 2))),
                                       rel=1e-12)


def test_the_model_is_scale_times_ratio_plus_offset():
    """The residuals must be the measured levels minus that expression, on the
    pattern entries the assignment names."""
    p = pattern("box_3d_cube")
    levels = _ladder("box_3d_cube", 5) + np.array([0.003, -0.002, 0.004,
                                                   0.0, -0.001])
    fit = fit_pattern(levels, 0.004, p)

    used = np.array([p.ratios[i] for i in fit.assignment])
    model = fit.scale_ev * used + fit.offset_ev
    np.testing.assert_allclose(np.sort(levels) - model, fit.residuals_ev,
                               rtol=1e-12, atol=1e-15)


@pytest.mark.parametrize("n, k, offset_fixed", [(4, 2, None), (5, 2, None),
                                                (4, 1, 0.02), (3, 1, 0.02)])
def test_aic_carries_the_small_sample_correction(n, k, offset_fixed):
    """AICc, not AIC. At three to five levels with two parameters the plain
    AIC under-penalises badly, and that is the whole operating regime."""
    levels = _ladder("box_1d", n) + 0.002
    fit = fit_pattern(levels, 0.004, pattern("box_1d"),
                      offset_fixed=offset_fixed)

    expected = fit.chi2 + 2.0 * k
    if n - k - 1 > 0:
        expected += 2.0 * k * (k + 1) / (n - k - 1)
    assert fit.aic == pytest.approx(expected, rel=1e-12)
    assert fit.dof == n - k


def test_fixing_the_offset_spends_one_parameter_not_two():
    """A supplied offset is not an undetermined quantity, so its error is
    exactly zero rather than NaN, and a degree of freedom is bought back."""
    levels = np.array([SCALE_EV * r for r in pattern("box_1d").ratios[:3]])
    fit = fit_pattern(levels, 0.003, pattern("box_1d"), offset_fixed=0.0)

    assert fit.offset_ev == 0.0
    assert fit.offset_err_ev == 0.0
    assert fit.dof == 2                      # n - k, k = 1
    assert fit.scale_ev == pytest.approx(SCALE_EV, rel=1e-9)


def test_the_error_bar_scales_the_uncertainty_and_not_the_answer():
    """Doubling sigma doubles the parameter error, quarters chi-squared, and
    leaves the least-squares solution exactly where it was."""
    levels = _ladder("box_1d", 4) + np.array([0.002, -0.003, 0.004, -0.001])
    tight = fit_pattern(levels, 0.002, pattern("box_1d"))
    loose = fit_pattern(levels, 0.004, pattern("box_1d"))

    assert loose.scale_ev == pytest.approx(tight.scale_ev, rel=1e-12)
    assert loose.offset_ev == pytest.approx(tight.offset_ev, rel=1e-12)
    assert loose.scale_err_ev == pytest.approx(2.0 * tight.scale_err_ev, rel=1e-12)
    assert loose.offset_err_ev == pytest.approx(2.0 * tight.offset_err_ev, rel=1e-12)
    assert loose.chi2 == pytest.approx(tight.chi2 / 4.0, rel=1e-12)


def test_the_fitted_scale_is_always_positive():
    """A negative scale runs the geometry backwards — it reproduces the order
    of the levels rather than their spacing — and is not a solution."""
    for name in PATTERN_NAMES:
        fit = fit_pattern(_ladder(name, 4), 0.004, pattern(name))
        assert fit.scale_ev > 0.0


# ---------------------------------------------------------------------------
# The guard — the worst failure mode this module could have
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("name", PATTERN_NAMES)
def test_two_levels_are_fitted_exactly_by_every_geometry(name):
    """The reason the guard exists, stated as a fact about the fits: with two
    free parameters and two levels chi-squared is zero for every pattern and
    there is nothing left to compare."""
    fit = fit_pattern([0.080, 0.190], 0.005, pattern(name))
    assert fit.chi2 == pytest.approx(0.0, abs=1e-18)
    assert fit.dof == 0


def test_two_levels_and_a_free_offset_is_refused():
    """MANDATORY. Returning a confident geometry here would be pure noise
    dressed as a result."""
    verdict = rank_patterns([0.080, 0.190], DISORDER_EV)

    assert verdict.verdict == UNDERDETERMINED
    assert verdict.best is None
    assert verdict.runner_up is None
    assert verdict.ranked == ()              # nothing readable as "the best"
    assert np.isnan(verdict.delta_aic)
    assert verdict.n_levels == 2


def test_the_refusal_still_reports_the_headline_ratio():
    """Refusing to rank is not refusing to measure: E2/E1 is a direct
    observation and survives the guard."""
    verdict = rank_patterns([0.060, 0.150], DISORDER_EV)
    assert verdict.ratio_21 == pytest.approx(2.5, rel=1e-12)
    assert verdict.ratio_21_err == pytest.approx(0.987, abs=0.002)


def test_a_known_offset_buys_the_third_level_back():
    """With the band edge supplied there is one free parameter, so two levels
    are one more than the minimum and the ranking may proceed."""
    verdict = rank_patterns([0.060, 0.150], 0.005, offset_fixed=0.0)

    assert verdict.verdict != UNDERDETERMINED
    assert verdict.best is not None
    assert verdict.best.dof == 1


def test_one_level_is_refused_even_with_the_offset_fixed():
    verdict = rank_patterns([0.060], 0.005, offset_fixed=0.0)
    assert verdict.verdict == UNDERDETERMINED
    assert verdict.best is None
    assert verdict.ranked == ()


def test_three_levels_are_the_minimum_with_a_fitted_offset():
    verdict = rank_patterns(_ladder("box_1d", 3), 0.005)
    assert verdict.verdict != UNDERDETERMINED
    assert verdict.n_levels == 3
    assert verdict.best.dof == 1


def test_a_ladder_longer_than_every_pattern_is_refused_not_truncated():
    """Eleven levels against eight-entry patterns: no fit exists, and the
    ranking must come back empty rather than quietly dropping levels."""
    levels = np.arange(1, 12) * 0.01
    verdict = rank_patterns(levels, 0.002)

    assert verdict.verdict == UNDERDETERMINED
    assert verdict.best is None
    assert verdict.ranked == ()
    assert np.isnan(verdict.delta_aic)


def test_an_empty_ladder_is_refused_and_does_not_raise():
    verdict = rank_patterns([], 0.005)
    assert verdict.verdict == UNDERDETERMINED
    assert verdict.n_levels == 0
    assert np.isnan(verdict.ratio_21)


# ---------------------------------------------------------------------------
# What the junction does to the ratios, and what it does not
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("eta", [0.35, 0.7, 1.4])
def test_a_constant_lever_arm_changes_the_scale_and_nothing_else(eta):
    """A bias-independent voltage division puts every level at V = E/eta. The
    fitted scale must absorb it exactly: same chi-squared, same AIC ordering,
    same verdict, same headline ratio."""
    levels = _ladder("box_2d_square", 5)
    noise = np.array([0.004, -0.003, 0.005, -0.002, 0.001])
    measured = levels + noise

    direct = rank_patterns(measured, 0.005)
    divided = rank_patterns(measured / eta, 0.005 / eta)

    assert divided.verdict == direct.verdict
    assert divided.best.pattern == direct.best.pattern
    assert divided.ratio_21 == pytest.approx(direct.ratio_21, rel=1e-12)

    # Every pattern's evidence is untouched; only the scale and the offset,
    # which carry the volt, move with eta.
    before = {f.pattern: f for f in direct.ranked}
    for after in divided.ranked:
        was = before[after.pattern]
        assert after.assignment == was.assignment, after.pattern
        assert after.chi2 == pytest.approx(was.chi2, rel=1e-9, abs=1e-18)
        assert after.aic == pytest.approx(was.aic, rel=1e-9), after.pattern
        assert after.scale_ev == pytest.approx(was.scale_ev / eta, rel=1e-9)
        assert after.offset_ev == pytest.approx(was.offset_ev / eta,
                                                rel=1e-9, abs=1e-15)


def test_charging_is_not_absorbable_by_a_scale_and_an_offset():
    """A term growing with the level index is neither a multiplier nor a
    constant. Unlike a lever arm it must leave residual behind."""
    p = pattern("box_1d")
    clean = np.array([SCALE_EV * r for r in p.ratios[:5]])
    charged = clean + 0.050 * np.arange(clean.size)

    assert fit_pattern(clean, 0.004, p).chi2 == pytest.approx(0.0, abs=1e-12)
    assert fit_pattern(charged, 0.004, p).chi2 > 20.0


def test_charging_pushes_successive_ratios_towards_one():
    """The diagnostic symptom. Adding an equal step per electron compresses
    the ladder from above, so every successive ratio above the ground level
    moves closer to 1 than the pure confinement ladder's."""
    p = pattern("box_1d")
    clean = np.array([SCALE_EV * r for r in p.ratios[:5]])
    charged = clean + 0.020 * np.arange(clean.size)

    clean_ratios = clean[1:] / clean[:-1]
    charged_ratios = charged[1:] / charged[:-1]

    # Skip the first: the ground level carries no charging term, so E2/E1 is
    # inflated rather than compressed. From the second step onwards the
    # arithmetic term dominates and drives every ratio down towards 1.
    assert np.all(charged_ratios[1:] < clean_ratios[1:])
    assert np.all(charged_ratios[1:] > 1.0)
    # In the limit of pure charging the ladder is arithmetic — one equal step
    # per electron, ground level included — and every ratio collapses onto
    # (k + 1) / k, i.e. towards 1.
    heavy = clean + 5.0 * np.arange(1, clean.size + 1)
    k = np.arange(1, clean.size)
    np.testing.assert_allclose(heavy[1:] / heavy[:-1], (k + 1.0) / k, rtol=0.02)
    assert np.all(np.diff(heavy[1:] / heavy[:-1]) < 0.0)


# ---------------------------------------------------------------------------
# The 2D-contains-1D degeneracy
# ---------------------------------------------------------------------------

def test_a_square_box_reproduces_the_line_exactly_on_a_short_ladder():
    """(n, 1) of a square is n^2 + 1 — the 1D ladder shifted — and a constant
    shift is exactly what the fitted offset absorbs. So the 2D fit is not
    merely good, it is perfect, at half the scale and a negative offset."""
    levels = _ladder("box_1d", 4)
    fit = fit_pattern(levels, 0.004, pattern("box_2d_square"))

    assert fit.chi2 == pytest.approx(0.0, abs=1e-18)
    assert fit.assignment == (0, 1, 3, 5)
    # The square's ratios are (nx^2 + ny^2) / 2, so matching n^2 + 1 against
    # them costs a factor of two in the scale and one ground level in the
    # offset: s2 = 2 s1, off2 = off1 - s1.
    assert fit.scale_ev == pytest.approx(2.0 * SCALE_EV, rel=1e-9)
    assert fit.offset_ev == pytest.approx(OFFSET_EV - SCALE_EV, rel=1e-9)


def test_that_degeneracy_is_reported_ambiguous_not_decided():
    """Two exact fits are not a discrimination. The verdict must say so."""
    verdict = rank_patterns(_ladder("box_1d", 4), 0.004)

    # Two fits reproducing the ladder equally well are NOT equal evidence when
    # one had to invent unresolved states to do it. Charging a parameter per
    # skip is what separates them, and the rival needing skips is the one that
    # loses -- so a clean box_1d ladder resolves rather than tying.
    assert verdict.best.pattern == "box_1d"
    assert verdict.best.n_skipped == 0
    assert verdict.runner_up.n_skipped > 0
    assert verdict.delta_aic >= AMBIGUITY_DELTA_AIC
    assert verdict.verdict == CONCLUSIVE


def test_a_tie_goes_to_the_fit_that_invents_fewest_unresolved_states():
    """AIC is indifferent between the two, so the tie-break decides: the 1D
    reading needs no skipped entries, the 2D one needs two."""
    verdict = rank_patterns(_ladder("box_1d", 4), 0.004)

    assert verdict.best.pattern == "box_1d"
    assert verdict.best.n_skipped == 0
    assert verdict.runner_up.n_skipped == 2


def test_a_longer_ladder_outruns_the_alias_and_becomes_conclusive():
    """The 2D reading consumes two pattern entries per measured level, so it
    runs out first. Five levels is enough to break the tie honestly."""
    verdict = rank_patterns(_ladder("box_1d", 5), 0.004)

    assert verdict.verdict == CONCLUSIVE
    assert verdict.best.pattern == "box_1d"
    assert verdict.delta_aic > AMBIGUITY_DELTA_AIC


# ---------------------------------------------------------------------------
# Unresolved states — skips
# ---------------------------------------------------------------------------

def test_unresolved_low_states_are_recovered_by_allowing_skips():
    """At ~29 meV resolution the weakest features are missed, and they are
    often the lowest ones. A ladder that starts at the second pattern entry
    must still be fitted exactly."""
    p = pattern("box_1d")
    levels = np.array([SCALE_EV * r + OFFSET_EV for r in p.ratios[1:5]])

    forbidden = fit_pattern(levels, 0.002, p, max_skips=0)
    allowed = fit_pattern(levels, 0.002, p, max_skips=2)

    assert forbidden.assignment == (0, 1, 2, 3)
    assert forbidden.chi2 > 100.0
    assert allowed.assignment == (1, 2, 3, 4)
    assert allowed.chi2 == pytest.approx(0.0, abs=1e-12)
    assert allowed.n_skipped == 1


def test_n_skipped_counts_the_pattern_entries_left_unmatched():
    """Because the assignment is strictly increasing, the count is exactly
    ``last_index - (n - 1)`` — skips before and between are the same thing."""
    fit = PatternFit(pattern="x", label="x", confined_dims=1, scale_ev=1.0,
                     scale_err_ev=0.0, offset_ev=0.0, offset_err_ev=0.0,
                     assignment=(0, 2, 5), chi2=0.0, dof=1,
                     p_value=float("nan"), k_eff=5, aic=0.0,
                     residuals_ev=(0.0, 0.0, 0.0), rms_ev=0.0)
    assert fit.n_skipped == 3


# ---------------------------------------------------------------------------
# Verdicts and the ranking
# ---------------------------------------------------------------------------

def test_the_ranking_is_ascending_in_aic():
    verdict = rank_patterns(_ladder("disc_2d", 5), 0.004)
    aics = np.array([f.aic for f in verdict.ranked])
    # Ascending to within the tie grid: two patterns that contain one another
    # exactly agree in the last digit, and which of those comes first is
    # settled by the number of states each had to invent, not by round-off.
    assert np.all(np.diff(aics) > -TIE_QUANTUM)
    assert verdict.best is verdict.ranked[0]
    assert verdict.runner_up is verdict.ranked[1]
    assert verdict.delta_aic == pytest.approx(aics[1] - aics[0], rel=1e-12)


@pytest.mark.parametrize("name", PATTERN_NAMES)
def test_the_verdict_is_always_one_of_the_three_stable_keys(name):
    verdict = rank_patterns(_ladder(name, 5), 0.004)
    assert verdict.verdict in VERDICTS
    assert verdict.note


def test_a_lone_surviving_pattern_gets_an_infinite_margin_not_a_tie():
    """Zero would read as "the two were compared and drew". Nothing was
    compared, so the margin is unbounded."""
    verdict = rank_patterns(_ladder("box_1d", 4), 0.004,
                            patterns=[pattern("box_1d")])

    assert verdict.runner_up is None
    assert verdict.delta_aic == float("inf")
    assert verdict.verdict == CONCLUSIVE
    assert "no rival" in verdict.note


def test_the_ambiguity_threshold_is_where_the_verdict_flips():
    """Burnham & Anderson's delta = 2: below it the runner-up has substantial
    support and the data has not chosen."""
    # Asserted as the contract over many realisations rather than from one
    # hand-built ladder: which dataset falls either side of the threshold is
    # an accident of the noise, but the correspondence never is.
    rng = np.random.default_rng(4242)
    truth = _ladder("box_2d_square", 5)

    seen = set()
    for _ in range(60):
        v = rank_patterns(np.sort(truth + rng.normal(0.0, 0.02, truth.size)),
                          0.02)
        if v.verdict in (AMBIGUOUS, CONCLUSIVE):
            assert (v.verdict == AMBIGUOUS) == (
                v.delta_aic < AMBIGUITY_DELTA_AIC), v.note
            seen.add(v.verdict)

    assert seen, "no comparable verdict in 60 realisations"


def test_by_default_every_known_geometry_is_compared():
    """A comparison that quietly left one geometry out would report a margin
    over a rival that was never in the race."""
    verdict = rank_patterns(_ladder("sphere_3d", 5), 0.004)
    assert {f.pattern for f in verdict.ranked} == {p.name for p in all_patterns()}


def test_only_the_listed_patterns_are_ranked():
    subset = [pattern("box_1d"), pattern("box_3d_cube")]
    verdict = rank_patterns(_ladder("box_3d_cube", 5), 0.004, patterns=subset)
    assert {f.pattern for f in verdict.ranked} == {"box_1d", "box_3d_cube"}


# ---------------------------------------------------------------------------
# The headline ratio
# ---------------------------------------------------------------------------

def test_the_headline_ratio_matches_hand_propagation():
    """The spec's worked example: levels near 60 and 150 meV with a 22 meV
    disorder amplitude give E2/E1 = 2.5 +/- 1.0."""
    ratio, err = ratio_with_error([0.060, 0.150], DISORDER_EV)

    expected = 0.150 / 0.060
    expected_err = expected * np.sqrt((DISORDER_EV / 0.060) ** 2
                                      + (DISORDER_EV / 0.150) ** 2)
    assert ratio == pytest.approx(2.5, rel=1e-12)
    assert err == pytest.approx(expected_err, rel=1e-12)
    assert err == pytest.approx(1.0, abs=0.05)


def test_that_error_bar_covers_3D_but_not_1D():
    """The consequence the module is built around: one spectrum separates a
    line from everything else, and does not separate a square from a cube."""
    _ratio, err = ratio_with_error([0.060, 0.150], DISORDER_EV)

    assert abs(2.5 - 2.0) < err          # a cube is inside the error bar
    assert abs(2.5 - 2.046) < err        # so is a sphere
    assert abs(2.5 - 4.0) > err          # a line is not


@pytest.mark.parametrize("name, expected", [("box_1d", 4.0),
                                            ("box_2d_square", 2.5),
                                            ("disc_2d", 2.5387),
                                            ("box_3d_cube", 2.0),
                                            ("sphere_3d", 2.0457)])
def test_the_textbook_ratio_comes_back_from_a_ladder_referred_to_the_edge(
        name, expected):
    """The numbers a reader recognises. They require the levels to be measured
    from the band edge, which is what the fitted offset is for elsewhere."""
    levels = _ladder(name, 2, offset=0.0)
    ratio, err = ratio_with_error(levels, 1e-6)
    assert ratio == pytest.approx(expected, abs=5e-4)
    assert err > 0.0


def test_fewer_than_two_levels_has_no_ratio():
    for levels in ([], [0.06]):
        ratio, err = ratio_with_error(levels, 0.005)
        assert np.isnan(ratio) and np.isnan(err)


@pytest.mark.parametrize("levels", [[0.0, 0.1], [-0.05, 0.1], [-0.2, -0.1]])
def test_a_non_positive_ground_level_is_nan_not_a_number(levels):
    """Dividing by a level at or below the band edge is not a confinement
    ratio, and NaN is the only honest answer."""
    ratio, err = ratio_with_error(levels, 0.005)
    assert np.isnan(ratio) and np.isnan(err)


def test_a_feature_at_the_band_edge_makes_the_ground_level_the_edge_itself():
    """Levels are sorted before the ratio is taken, so a feature sitting on
    the edge becomes E1 and the answer is NaN rather than a division by
    something arbitrarily small."""
    assert np.isnan(ratio_with_error([0.150, 0.0], 0.005)[0])

    # Two unresolved features at the same energy are a ratio of 1, which is
    # a real reading ("no spacing measured"), not an undefined one.
    ratio, err = ratio_with_error([0.05, 0.05], [0.01, 0.02])
    assert ratio == pytest.approx(1.0)
    assert np.isfinite(err) and err > 0.0


# ---------------------------------------------------------------------------
# Cleaning the input: NaN, order, and the error bars
# ---------------------------------------------------------------------------

def test_a_non_finite_level_is_dropped_and_the_count_says_so():
    levels = [0.080, float("nan"), 0.260, 0.560, 0.980]
    verdict = rank_patterns(levels, 0.004)

    assert verdict.n_levels == 4
    assert verdict.best is not None
    assert verdict.best.chi2 == pytest.approx(0.0, abs=1e-12)


def test_a_level_with_no_error_bar_is_dropped_not_given_infinite_weight():
    """Regression: the weight is 1/sigma^2, so flooring a non-finite sigma at
    MIN_SIGMA_EV made the one unmeasurable level dominate the entire fit."""
    good = _ladder("box_1d", 4)
    levels = np.concatenate([good, [0.400]])          # a spurious feature
    sigma = [0.004, 0.004, 0.004, 0.004, float("inf")]

    fit = fit_pattern(levels, sigma, pattern("box_1d"))
    assert fit.chi2 == pytest.approx(0.0, abs=1e-12)
    assert len(fit.residuals_ev) == 4
    assert fit.scale_ev == pytest.approx(SCALE_EV, rel=1e-9)


def test_a_zero_error_bar_is_floored_rather_than_dividing_by_zero():
    """Unlike a non-finite sigma, a zero one is a caller saying "no error
    bar", not "no information", so the level is kept."""
    fit = fit_pattern(_ladder("box_1d", 4), 0.0, pattern("box_1d"))
    assert fit is not None
    assert np.isfinite(fit.chi2)
    assert fit.scale_err_ev == pytest.approx(0.0, abs=10 * MIN_SIGMA_EV)


def test_the_levels_may_arrive_in_any_order():
    ascending = _ladder("box_2d_square", 4)
    shuffled = ascending[[2, 0, 3, 1]]

    a = fit_pattern(ascending, 0.004, pattern("box_2d_square"))
    b = fit_pattern(shuffled, 0.004, pattern("box_2d_square"))
    assert a == b


def test_a_per_level_sigma_follows_the_levels_through_the_sort():
    """Regression: dropping and sorting both reorder, so an independently
    cleaned sigma array puts the third level's error bar on the second."""
    ratio, err = ratio_with_error([0.150, 0.060], [0.030, 0.010])

    # After sorting, E1 = 0.060 carries sigma 0.010 and E2 = 0.150 carries
    # 0.030 — not the other way round.
    expected = 2.5 * np.sqrt((0.010 / 0.060) ** 2 + (0.030 / 0.150) ** 2)
    assert ratio == pytest.approx(2.5, rel=1e-12)
    assert err == pytest.approx(expected, rel=1e-12)


def test_a_mismatched_sigma_length_is_an_error_not_a_wrong_number():
    with pytest.raises(ValueError, match="sigma_ev has 3 values"):
        fit_pattern([0.06, 0.15], [0.01, 0.02, 0.03], pattern("box_1d"))


def test_an_all_nan_ladder_produces_no_fit_rather_than_a_guess():
    assert fit_pattern([float("nan")] * 4, 0.004, pattern("box_1d")) is None


# ---------------------------------------------------------------------------
# Turning a scale back into a length
# ---------------------------------------------------------------------------

def test_the_one_dimensional_size_is_the_textbook_inversion():
    """The oracle is the closed form, not the module: E1 = hbar^2 pi^2 /
    (2 m L^2). It also pins the unit — an inversion routed through the
    joules-returning entry point would come back ten orders of magnitude
    wrong while still looking like a positive length."""
    meff, length_nm = 0.067, 5.0
    ground_ev = (hbar ** 2 * pi ** 2
                 / (2.0 * meff * m_e * (length_nm * 1e-9) ** 2) / e)

    assert size_from_scale(ground_ev, pattern("box_1d"), meff) == pytest.approx(
        length_nm, rel=1e-9)


def _true_ground_ev(name, length_nm, meff):
    """The real ground level of that geometry at that size, in eV.

    Taken from :mod:`src.physics.analytical` directly, and from its
    eV-returning entry points only — ``box_energies_1d`` and
    ``box_energies_3d`` hand back joules.
    """
    from src.physics.analytical import (box_energies_1d_eV, box_energies_2d_eV,
                                        box_energies_3d_eV, disk_energies)
    from src.physics.quantum_dot import DOT_SPHERICAL, dot_energies

    if name == "box_1d":
        return box_energies_1d_eV(length_nm, meff, 1)[0][0]
    if name == "box_2d_square":
        return box_energies_2d_eV(length_nm, length_nm, meff, 1)[0][0]
    if name == "disc_2d":
        return disk_energies(length_nm, meff, 1)[0][0]
    if name == "box_3d_cube":
        return box_energies_3d_eV(length_nm, length_nm, length_nm, meff, 1)[0][0]
    return dot_energies(DOT_SPHERICAL, (length_nm,), meff, 1)[0][0]


@pytest.mark.parametrize("name, length_nm", [("box_1d", 5.0),
                                             ("box_2d_square", 7.0),
                                             ("disc_2d", 6.0),
                                             ("box_3d_cube", 4.0),
                                             ("sphere_3d", 3.5)])
def test_every_single_length_geometry_round_trips(name, length_nm):
    """Generate the geometry's true ground level, hand it back as the fitted
    scale, and the length must return — which also pins the geometry the
    inversion picked, since the five constants differ."""
    meff = 0.067
    ground = _true_ground_ev(name, length_nm, meff)

    assert size_from_scale(ground, pattern(name), meff) == pytest.approx(
        length_nm, rel=1e-9)
    assert 0.01 < ground < 5.0, "a joules ladder would land near 1e-20"


def test_the_size_is_an_inverse_square_root_in_both_the_scale_and_the_mass():
    """E ~ 1/(m L^2) exactly, so both dependences are fixed and neither can
    change the verdict — the ranking never sees the mass at all."""
    p = pattern("box_3d_cube")
    base = size_from_scale(0.10, p, 0.067)

    assert size_from_scale(0.40, p, 0.067) == pytest.approx(base / 2.0, rel=1e-9)
    assert size_from_scale(0.10, p, 4 * 0.067) == pytest.approx(base / 2.0,
                                                                rel=1e-9)


def test_a_geometry_of_two_lengths_has_no_single_size():
    """A 2:1 rectangle and a cylinder both need two lengths; one scale cannot
    supply them, and NaN is the point rather than a shortcoming."""
    from src.physics.analytical import box_energies_2d_eV, cylinder_energies

    raw = box_energies_2d_eV(1.0, 2.0, 1.0, 8)
    rectangle = _fake_pattern([E / raw[0][0] for E, _ in raw])
    assert np.isnan(size_from_scale(0.1, rectangle, 0.067))

    distinct = []
    for energy, _qn in cylinder_energies(1.0, 3.0, 1.0, 40):
        if not distinct or energy - distinct[-1] > 1e-9 * distinct[-1]:
            distinct.append(energy)
    cylinder = _fake_pattern([E / distinct[0] for E in distinct[:8]], dims=3)
    assert np.isnan(size_from_scale(0.1, cylinder, 0.067))


@pytest.mark.parametrize("scale, meff", [(0.0, 0.067), (-0.1, 0.067),
                                         (float("nan"), 0.067),
                                         (0.1, 0.0), (0.1, -0.067),
                                         (0.1, float("nan"))])
def test_a_non_positive_scale_or_mass_gives_nan(scale, meff):
    assert np.isnan(size_from_scale(scale, pattern("box_1d"), meff))


def test_a_pattern_with_one_ratio_has_nothing_to_match_on():
    assert np.isnan(size_from_scale(0.1, _fake_pattern([1.0], dims=1), 0.067))


# ---------------------------------------------------------------------------
# What one spectrum can and cannot decide
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("name", ["box_1d", "box_2d_square", "box_3d_cube"])
def test_one_disordered_spectrum_is_almost_never_conclusive(name):
    """The spec's prediction, and the reason a map is needed: at 22 meV
    disorder on four levels the per-point verdict is 'ambiguous' nearly every
    time. The discrimination lives in the distribution, not in one point."""
    rng = np.random.default_rng(20260902)
    truth = np.array([SCALE_EV * r for r in pattern(name).ratios[:4]])

    verdicts = []
    for _ in range(40):
        measured = truth + rng.normal(0.0, DISORDER_EV, truth.size)
        verdicts.append(rank_patterns(np.sort(measured), DISORDER_EV).verdict)

    conclusive = verdicts.count(CONCLUSIVE)
    # Split by what the physics allows, which the spec's blanket "almost never
    # conclusive" got wrong. That prediction came from propagating the
    # disorder onto E2/E1 alone -- a TWO-level argument -- and a four-level
    # joint fit carries more information than two levels do. What survives is
    # the separation the ratios themselves predict: 1D sits at 4.00, far from
    # everything else, and is identifiable from a single spectrum; 2.50
    # against 2.00 is not, and stays a distribution-level question.
    if name == "box_1d":
        assert conclusive >= 15, f"only {conclusive}/40 conclusive for 1D"
    else:
        assert conclusive <= 12, f"{conclusive}/40 conclusive for {name}"
        assert verdicts.count(AMBIGUOUS) >= 20


def test_the_geometry_is_recoverable_once_the_noise_is_below_the_spacing():
    """The complementary statement: the module is not simply unable to decide.
    Shrink the disorder to a fifth of the level spacing and the truth comes
    back as `best` for every geometry."""
    rng = np.random.default_rng(7)
    sigma = 0.002
    for name in PATTERN_NAMES:
        truth = _ladder(name, 6)
        measured = np.sort(truth + rng.normal(0.0, sigma, truth.size))
        verdict = rank_patterns(measured, sigma)
        assert verdict.best.pattern == name, name
